# Generated by Django 6.0.3 on 2026-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مانند آیدین ', max_length=20, verbose_name='نام')),
                ('email', models.EmailField(help_text='مثل: yourname@xyz.com', max_length=254, verbose_name='رایانامه')),
                ('subject', models.IntegerField(choices=[(0, 'درخواست کمک'), (1, 'گزارش اشکال'), (2, 'پیشنهاد همکاری'), (3, 'انتقاد و ایده برای بهبود')], default=0, help_text='علّت تماس شما', verbose_name='موضوع')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('message', models.TextField(help_text='جاپیامی', verbose_name='پیام')),
                ('spam_status', models.IntegerField(choices=[(-1, 'Not Specified'), (0, 'OK'), (1, 'Spam')], default=-1, verbose_name='وضعیّت پیام')),
            ],
        ),
    ]
