# Generated by Django 4.2.3 on 2023-11-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                help_text="مثل: yourname@xyz.com",
                max_length=254,
                verbose_name="رایانامه",
            ),
        ),
    ]
