# Generated by Django 6.0.3 on 2026-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_website_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='screenshot',
        ),
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20),
        ),
    ]
