# Generated by Django 6.0.3 on 2026-04-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_tag_alter_category_options_alter_website_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='bi-folder', max_length=50),
        ),
        migrations.AlterField(
            model_name='website',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_set', to='directory.category'),
        ),
        migrations.AlterField(
            model_name='website',
            name='hide_owner_info',
            field=models.BooleanField(default=False, verbose_name='مخفی کردن اطلاعات'),
        ),
    ]
